name: addReadmeToRelease

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  deploy:
  
    runs-on: ubuntu-latest
    steps:
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        with:
          file: "*.md"
          tags: false
          draft: false
