# This is a basic workflow to help you get started with Actions

name: Build and Deploy on Release

# Controls when the workflow will run
on:
  release:
    types: [published]

run-name: Release ${{ github.event.release.tag_name }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DeployAndUpdateRelease:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements.txt

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        GET_RELEASE_NAME_AUTH_TOKEN: ${{ secrets.GET_RELEASE_NAME_AUTH_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
        
    - name: Upload Dist to Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "dist/*"
        overwrite: true
        draft: false
        tag_name: ${{ github.event.release.tag_name }}

