# This is a basic workflow to help you get started with Actions

name: Make Release And Deploy On PR.yml

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  MakeRelease:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create Release with readme
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "README.md"
          overwrite: true
          draft: false
          tag_name: ${{ github.event.pull_request.title }}

  DeployAndUpdateRelease:

    needs: MakeRelease
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements.txt

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        GET_RELEASE_NAME_AUTH_TOKEN: ${{ secrets.GET_RELEASE_NAME_AUTH_TOKEN }}
      run: |
        git pull
        python setup.py sdist bdist_wheel
        twine upload dist/*
        
    - name: Upload Dist to Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "dist/*"
        overwrite: true
        draft: false
        tag_name: ${{ github.event.pull_request.title }}
